version: 2
jobs:
  test:
    docker:
    - image: circleci/node:8.11

    steps:
    - checkout

    - restore_cache:
        keys:
        - dependency-cache-{{ checksum "package.json" }}

    - run:
        name: install dependencies
        command: yarn install

    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules

    - run:
        name: lint
        command: yarn run lint

    - run:
        name: build
        command: yarn run build

workflows:
  version: 2
  all_jobs:
    jobs:
    - test
